<?php

	require APPPATH . '/libraries/REST_Controller.php';

	// use namespace
	use Restserver\Libraries\REST_Controller;


class Login extends REST_Controller
{


	public function index_get($value='')
	{
		$npk 	 = $this->get('npk'); 
		$pass  	 = $this->get('password'); 
        $where = [
            'npk' 			=> $npk, // Automatically generated by the model
            'password' 		=> $pass,
        ];

        $count = $this->m_presensi->cekLogin($where)->num_rows();
        	if($count > 0 ){
        		$data = $this->m_presensi->cekLogin($where)->result_array();
        		$this->set_response([
        			'status' 	  => $count ,
        			'response'    => "Ok" ,
        			'data'     	 => $data 
        		],REST_Controller::HTTP_OK);
        	}else {
        		$this->set_response([
        			'status' 	  => $count ,
        			'response'    => "user tidak ada" ,
        		],200);
        	}
	}


}