<?php

	require APPPATH . '/libraries/REST_Controller.php';

	// use namespace
	use Restserver\Libraries\REST_Controller;


class Presensi extends REST_Controller
{


	public function absen_post($value='')
	{
        $data = [
            'nama' 		=> $this->post('nama'), // Automatically generated by the model
            'npk' 		=> $this->post('npk'),
            'tanggal' 	=> $this->post('tanggal'),
        ];


       $simpan =  $this->db->insert("absensi",$data);

       	if($simpan){
       		$message = [
                'nama' 		=> $this->post('nama'), // Automatically generated by the model
	            'npk' 		=> $this->post('npk'),
	            'tanggal' 	=> $this->post('tanggal'),
	            'masuk' 	=> $this->post('masuk') ,
	            'status'	=> "OK",
                'message'   => 'Data Tersimpan' ,
       		];
       		$this->set_response($message, REST_Controller::HTTP_CREATED); // NOT_FOUND (404) being the HTTP response code
       	}
	}



	public function absen_put()
	{
		date_default_timezone_set('Asia/Jakarta');
		$id			 = $this->put('id');
        $tanggal 	 = $this->put('tanggal');
        $npk   		 = $this->put("npk");
        $nama        = $this->put("nama");

        $jadwal = $this->m_presensi->get_Jadwal(array("id" => $id))->row();
        if($jadwal->masuk == "00:00:00"){
        	$data = array(
        		'masuk'		=> date('H:i:s')
        	);

        	$update = $this->m_presensi->createAbsen($data,array("id" => $id));
        	if($update){
	            $this->response([
	            	'status'    => "Ok" ,
	            	'message'   => "Presensi Masuk Sukses"
	            ], 200);
        	}else {
        		 $this->set_response([
	            	'status'    => "Failed" ,
	            ], REST_Controller::HTTP_BAD_REQUEST);
        	}
        }else if($jadwal->masuk != "00:00:00" && $jadwal->pulang == "00:00:00" ){
        	$data = array(
        		'pulang'		=> date('H:i:s')
        	);

        	$update = $this->m_presensi->createAbsen($data,array("id" => $id));
        	if($update){
	            $this->response([
	            	'status'    => "Ok" ,
	            	'message'   => "Presensi Pulang Sukses"
	            ], 200);
        	}else {
        		 $this->set_response([
	            	'status'    => "Failed" ,
	            ], REST_Controller::HTTP_BAD_REQUEST);
        	}
        }else if($jadwal->masuk != "00:00:00" && $jadwal->pulang != "00:00:00"){
        	$this->set_response([
        		'status'   => "sudah presensi pulang pergi" 
        	],200);
        }

	}
}